language: generic
services:
  - docker

before_install:
  - docker build -t speudyland/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true speudyland/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-714555244835"
  bucket_path: "docker-react"
  # No stash entries found.
  # https://stackoverflow.com/questions/58908074/no-stash-entries-found-missing-bucket-name
  # edge: true
  skip_cleanup: true
  # push only when we deploy on the master branch
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
